site_name: SVW Results
site_description: RWK Results from SV Wappersdorf e.V.
site_author: SV Wappersdorf e.V. (Dischner Alexander)

theme: 
  name: mkdocs

nav: 
 - Home: index.md
 - RWK Ergebnisse LG 2024/2025: 
      - Vorrunde 1: results_2025_luftgewehr_vorrunde_1.md
      - Vorrunde 2: results_2025_luftgewehr_vorrunde_2.md
      - Vorrunde 3: results_2025_luftgewehr_vorrunde_3.md
      - Vorrunde 4: results_2025_luftgewehr_vorrunde_4.md
      - Vorrunde 5: results_2025_luftgewehr_vorrunde_5.md
      - Vorrunde 6: results_2025_luftgewehr_vorrunde_6.md
      - Vorrunde 7: results_2025_luftgewehr_vorrunde_7.md
      - Vorrunde 8: results_2025_luftgewehr_vorrunde_8.md
      - Vorrunde 9: results_2025_luftgewehr_vorrunde_9.md
      - Rückrunde 1: results_2025_luftgewehr_rückrunde_1.md
      - Rückrunde 2: results_2025_luftgewehr_rückrunde_2.md
      - Rückrunde 3: results_2025_luftgewehr_rückrunde_3.md
      - Rückrunde 4: results_2025_luftgewehr_rückrunde_4.md
      - Rückrunde 5: results_2025_luftgewehr_rückrunde_5.md
      - Rückrunde 6: results_2025_luftgewehr_rückrunde_6.md
      - Rückrunde 7: results_2025_luftgewehr_rückrunde_7.md
      - Rückrunde 8: results_2025_luftgewehr_rückrunde_8.md
      - Rückrunde 9: results_2025_luftgewehr_rückrunde_9.md
 - RWK Ergebnisse LP 2024/2025:
      - Vorrunde 1: results_2025_luftpistole_vorrunde_1.md
      - Vorrunde 2: results_2025_luftpistole_vorrunde_2.md
      - Vorrunde 3: results_2025_luftpistole_vorrunde_3.md
      - Vorrunde 4: results_2025_luftpistole_vorrunde_4.md
      - Vorrunde 5: results_2025_luftpistole_vorrunde_5.md
      - Vorrunde 6: results_2025_luftpistole_vorrunde_6.md
      - Vorrunde 7: results_2025_luftpistole_vorrunde_7.md
      - Vorrunde 8: results_2025_luftpistole_vorrunde_8.md
      - Vorrunde 9: results_2025_luftpistole_vorrunde_9.md
      - Rückrunde 1: results_2025_luftpistole_rückrunde_1.md
      - Rückrunde 2: results_2025_luftpistole_rückrunde_2.md
      - Rückrunde 3: results_2025_luftpistole_rückrunde_3.md
      - Rückrunde 4: results_2025_luftpistole_rückrunde_4.md
      - Rückrunde 5: results_2025_luftpistole_rückrunde_5.md
      - Rückrunde 6: results_2025_luftpistole_rückrunde_6.md
      - Rückrunde 7: results_2025_luftpistole_rückrunde_7.md
      - Rückrunde 8: results_2025_luftpistole_rückrunde_8.md