on:
  push:
    branches: ["main", "docs"]
    changes:
      - "svw-results/**"

jobs:
  pages:
    script:
      - pip install -r requirements.txt
      - mkdocs gh-deploy
    artifacts:
      paths:
        - public
    only:
      - main
      - docs