on:
  push:
    branches: ["main", "docs"]
    # changes:
    #   - "svw-results/**"

jobs:
  pages:
    steps:
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy
    artifacts:
      paths:
        - public