on:
  push:
    branches: ["main", "docs"]
    # changes:
    #   - "svw-results/**"

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - run: pip install -r ${{ github.repository }}/requirements.txt
      - run: mkdocs gh-deploy
