on:
  push:
    branches: ["main", "docs"]
    # changes:
    #   - "svw-results/**"

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for the gh-deploy action
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: git config
        run: |
          git fetch
      - name: Build and deploy
        run: |
          mkdocs build --config-file ./svw-results/mkdocs.yml
          mkdocs gh-deploy --config-file ./svw-results/mkdocs.yml
